version: '3'
services:
  fastapi:
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    build:
      context: backend
      dockerfile: Docker/fastapi/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "8000:8000"
  flask:
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    build:
      context: backend
      dockerfile: Docker/flask/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "5000:5000"

